# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"

# http://docs.travis-ci.com/user/gui-and-headless-browsers
before_install:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - npm install

# http://docs.travis-ci.com/user/pull-requests/
script:
  - npm test
